apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: task-service

  template:
    metadata:
      labels:
        app: task-service

    spec:
      containers:
      - name: task-service
        image: mrudul08/task-service:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
